CREATE DATABASE qcop CHARACTER SET utf8;

CREATE TABLE user_base (
id SERIAL PRIMARY KEY,
email VARCHAR(255) NOT NULL,
user_name VARCHAR (255) NOT NULL,
user_surname VARCHAR (255) NOT NULL,
mail_url VARCHAR (255) NOT NULL,
used TINYINT NOT NULL,
create_date DATETIME NOT NULL
)ENGINE=MyISAM;

ALTER TABLE user_base ADD gender TINYINT NOT NULL AFTER user_surname;
